project_name: nanofibrous_budded
before:
  hooks:
  - go mod tidy
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
checksum:
  name_template: checksums.txt
snapshot:
  version_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
